// via54Design — 设计模板引擎 + 叙事引擎
// Copyright (C) 2026  via54 (veawho)
//
// SPDX-License-Identifier: AGPL-3.0-only

package pipeline

import (
	"fmt"
	"strings"
)

// BuildRawPrompt builds a combined prompt string from scaffold fields.
func BuildRawPrompt(scaffold *PromptScaffold) string {
	var parts []string
	for _, field := range DimensionFields {
		if val, ok := scaffold.Fields[field]; ok && val != "" {
			parts = append(parts, val)
		}
	}

	prompt := strings.Join(parts, ", ")
	if len(scaffold.Negative) > 0 {
		negStr := strings.Join(scaffold.Negative, ", ")
		prompt += " --negative " + negStr
	}
	return prompt
}

// ExportA1111 formats the scaffold for Automatic1111 / SD.Next.
func ExportA1111(scaffold *PromptScaffold) string {
	var positiveParts []string
	for _, field := range DimensionFields {
		if val, ok := scaffold.Fields[field]; ok && val != "" {
			positiveParts = append(positiveParts, val)
		}
	}

	positive := strings.Join(positiveParts, ", ")
	negative := strings.Join(scaffold.Negative, ", ")

	var b strings.Builder
	b.WriteString("# Automatic1111 / SD.Next Prompt Export\n")
	b.WriteString("# Generated by via54Design pipeline\n")
	b.WriteString("\n")
	b.WriteString("Positive prompt:\n")
	b.WriteString(positive)
	b.WriteString("\n\n")

	if negative != "" {
		b.WriteString("Negative prompt:\n")
		b.WriteString(negative)
		b.WriteString("\n\n")
	}

	b.WriteString("Settings:\n")
	b.WriteString("    Steps: 20\n")
	b.WriteString("    CFG Scale: 7.0\n")
	b.WriteString("    Sampler: DPM++ 2M Karras\n")
	b.WriteString("    Seed: -1\n")
	b.WriteString("    Size: 1024x1024\n")
	b.WriteString("\n")
	b.WriteString("# To use in A1111:\n")
	b.WriteString("# 1. Copy Positive prompt into the txt2img prompt field\n")
	b.WriteString("# 2. Copy Negative prompt into the negative prompt field\n")
	b.WriteString("# 3. Apply the settings above\n")
	b.WriteString("# 4. Click Generate\n")

	return b.String()
}

// ExportComfyUI formats the scaffold for ComfyUI CLIPTextEncode nodes.
func ExportComfyUI(scaffold *PromptScaffold, nodeID string) string {
	if nodeID == "" {
		nodeID = "6"
	}

	var positiveParts []string
	for _, field := range DimensionFields {
		if val, ok := scaffold.Fields[field]; ok && val != "" {
			positiveParts = append(positiveParts, val)
		}
	}

	positive := strings.Join(positiveParts, ", ")
	negative := strings.Join(scaffold.Negative, ", ")

	negNode := "7"
	if nodeID != "6" {
		// Try to compute sibling node
		var n int
		_, err := fmt.Sscanf(nodeID, "%d", &n)
		if err == nil {
			negNode = fmt.Sprintf("%d", n+1)
		}
	}

	var b strings.Builder
	b.WriteString("# ComfyUI CLIPTextEncode Export\n")
	b.WriteString("# Generated by via54Design pipeline\n")
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("## Node %s — CLIPTextEncode (positive):\n", nodeID))
	b.WriteString(positive)
	b.WriteString("\n\n")

	if negative != "" {
		b.WriteString(fmt.Sprintf("## Node %s — CLIPTextEncode (negative):\n", negNode))
		b.WriteString(negative)
		b.WriteString("\n\n")
	}

	b.WriteString("# To use in ComfyUI:\n")
	b.WriteString("# 1. Add two CLIPTextEncode nodes\n")
	b.WriteString(fmt.Sprintf("# 2. Paste positive prompt into node %s\n", nodeID))
	b.WriteString(fmt.Sprintf("# 3. Paste negative prompt into node %s\n", negNode))
	b.WriteString("# 4. Connect node outputs to your model's CLIP input\n")
	b.WriteString("# 5. Connect KSampler accordingly\n")

	return b.String()
}

// BrowserSubmit generates executable instructions for browser automation.
func BrowserSubmit(scaffold *PromptScaffold, platform string) string {
	prompt := scaffold.RawPrompt
	if prompt == "" {
		prompt = BuildRawPrompt(scaffold)
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("# P7 Browser MCP — Submit to %s\n", platform))
	b.WriteString("\n")
	b.WriteString("## 1. Final prompt to submit:\n")
	b.WriteString(prompt)
	b.WriteString("\n\n")
	b.WriteString("## 2. Browser Use MCP command sequence:\n")
	b.WriteString("\n")

	switch platform {
	case "midjourney":
		b.WriteString("# Navigate to Midjourney Discord (or Midjourney web app)\n")
		b.WriteString("browser goto https://www.midjourney.com/imagine\n")
		b.WriteString("\n")
		b.WriteString("# Type prompt into the input field\n")
		b.WriteString(fmt.Sprintf("browser type \"#imagine %s\"\n", prompt))
		b.WriteString("\n")
		b.WriteString("# Or use the Discord channel:\n")
		b.WriteString("browser type \"/imagine\"\n")
		b.WriteString(fmt.Sprintf("browser type \"%s\"\n", prompt))
		b.WriteString("browser press Enter\n")
	case "dalle":
		b.WriteString("browser goto https://www.bing.com/create\n")
		b.WriteString(fmt.Sprintf("browser type \"%s\"\n", prompt))
		b.WriteString("browser click 'Create' button\n")
	case "stable-diffusion", "flux":
		b.WriteString("# For Automatic1111 WebUI:\n")
		b.WriteString("browser goto http://127.0.0.1:7860\n")
		b.WriteString(fmt.Sprintf("browser type \"#txt2img_prompt\" \"%s\"\n", prompt))
		b.WriteString("browser click '#txt2img_generate'\n")
		b.WriteString("\n")
		b.WriteString("# For ComfyUI: Paste via workflow node\n")
		b.WriteString(fmt.Sprintf("# Load prompt into CLIPTextEncode node: %s\n", prompt))
	default:
		b.WriteString(fmt.Sprintf("# Generic browser-based submission for %s\n", platform))
		b.WriteString("# 1. Open the platform's web interface\n")
		b.WriteString("# 2. Paste the prompt into the text input\n")
		b.WriteString("# 3. Click the generate/submit button\n")
		b.WriteString("\n")
		b.WriteString(fmt.Sprintf("Prompt: %s\n", prompt))
	}

	b.WriteString("\n")
	b.WriteString("## 3. Playwright (Python) equivalent:\n")
	b.WriteString("# Requires: pip install playwright\n")
	b.WriteString("# from playwright.sync_api import sync_playwright\n")
	b.WriteString("\n")
	b.WriteString("## 4. Browser Use MCP tool call:\n")
	b.WriteString(fmt.Sprintf("# Submit via tool: browser_submit with content:\n"))
	shortPrompt := prompt
	if len(shortPrompt) > 200 {
		shortPrompt = shortPrompt[:200] + "..."
	}
	b.WriteString(fmt.Sprintf("# %s\n", shortPrompt))

	return b.String()
}
